AppControlLaboratorios/Models/Asistencia.cs
namespace AppControlLaboratorios.Models
{
    public class Asistencia
    {
        public int Id { get; set; }
        public DateTime Fecha { get; set; }
        public string Observaciones { get; set; }
        public int UsuarioId { get; set; }
        public virtual Usuario Usuario { get; set; }
        public int MaquinaId { get; set; }
        public virtual Maquina Maquina { get; set; }
        public int HorarioId { get; set; }
        public virtual Horario Horario { get; set; }
    }
}

AppControlLaboratorios/Controllers/AsistenciasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppControlLaboratorios.Data;
using AppControlLaboratorios.Models;

namespace AppControlLaboratorios.Controllers
{
    public class AsistenciasController : Controller
    {
        private readonly BDContexto _context;

        public AsistenciasController(BDContexto context)
        {
            _context = context;
        }

        // GET: Asistencias
        public async Task<IActionResult> Index(DateTime? fecha, int? idlab, int? idhorario)
        {
            // Obtener listas de laboratorios y horarios
            var laboratorios = await _context.Laboratorios.ToListAsync();
            var horarios = await _context.Horarios.ToListAsync();

            // Crear listas select para la vista
            ViewBag.Laboratorios = new SelectList(laboratorios, "Id", "LaboratorioNombre");
            ViewBag.Horarios = new SelectList(horarios, "Id", "CursoId");
            ViewBag.SelectedFecha = fecha;
            ViewBag.SelectedLab = idlab;
            ViewBag.SelectedHorario = idhorario;

            // Crear consulta inicial para las asistencias
            var bDContexto = _context.Asistencias
                .Include(a => a.Horario)
                .ThenInclude(c => c.Curso) // Relación entre Horario y Laboratorio
                .Include(a => a.Usuario) // Incluye la relación con Usuario
                .Include(a => a.Maquina) // Incluye la relación con Maquina
                .AsQueryable();


            // Filtro por Fecha
            if (fecha.HasValue)
            {
                bDContexto = bDContexto.Where(a =>
                    a.Fecha.Year == fecha.Value.Year &&
                    a.Fecha.Month == fecha.Value.Month &&
                    a.Fecha.Day == fecha.Value.Day);
            }


            // Filtro por Laboratorio
            if (idlab.HasValue && idlab.Value != 0)
            {
                bDContexto = bDContexto.Where(a => a.Maquina.LaboratorioId == idlab.Value);
            }

            // Filtro por Horario (HoraIni o HoraFin)
            if (idhorario.HasValue && idhorario.Value != 0)
            {
                bDContexto = bDContexto.Where(a => a.HorarioId == idhorario.Value);
            }

            // Obtener lista filtrada de asistencias
            var asistencias = await bDContexto.ToListAsync();

            return View(asistencias);
        }

        // GET: Asistencias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asistencia = await _context.Asistencias
                .Include(a => a.Horario)
                .Include(a => a.Maquina)
                .Include(a => a.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asistencia == null)
            {
                return NotFound();
            }

            return View(asistencia);
        }

        // GET: Asistencias/Create
        public IActionResult Create(int usuarioId, int maquinaId)
        {
            //Para que el reemplazar al horarioID
            var horarios = _context.Horarios
                .Include(h => h.Curso)  // Asegúrate de incluir la relación con el curso
                .Select(h => new {
                    h.Id,
                    DisplayText = h.Curso.CursoNombre + " (" + h.HoraIni + " - " + h.HoraFin + ")" // Formatear el texto para mostrarlo
                })
                .ToList();

            // Generar la lista de selección con el DisplayText personalizado
            ViewData["HorarioId"] = new SelectList(horarios, "Id", "DisplayText");

            var usuario = _context.Usuarios.Find(usuarioId);
            var maquina = _context.Maquinas.Find(maquinaId);
            var asistencia = new Asistencia
            {
                Usuario = usuario,
                Maquina = maquina,
                UsuarioId = usuarioId,
                MaquinaId = maquinaId
            };

            return View(asistencia);
        }


        // POST: Asistencias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Fecha,Observaciones,UsuarioId,MaquinaId,HorarioId")] Asistencia asistencia)
        {
            if (ModelState.IsValid)
            {
                asistencia.Fecha = DateTime.Now;
                _context.Add(asistencia);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["HorarioId"] = new SelectList(_context.Horarios, "Id", "Id", asistencia.HorarioId);
            return View(asistencia);
        }

        // GET: Asistencias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asistencia = await _context.Asistencias.FindAsync(id);
            if (asistencia == null)
            {
                return NotFound();
            }
            ViewData["HorarioId"] = new SelectList(_context.Horarios, "Id", "Id", asistencia.HorarioId);
            ViewData["MaquinaId"] = new SelectList(_context.Maquinas, "Id", "Id", asistencia.MaquinaId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Id", asistencia.UsuarioId);
            return View(asistencia);
        }

        // POST: Asistencias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Fecha,Observaciones,UsuarioId,MaquinaId,HorarioId")] Asistencia asistencia)
        {
            if (id != asistencia.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(asistencia);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AsistenciaExists(asistencia.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["HorarioId"] = new SelectList(_context.Horarios, "Id", "Id", asistencia.HorarioId);
            ViewData["MaquinaId"] = new SelectList(_context.Maquinas, "Id", "Id", asistencia.MaquinaId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Id", asistencia.UsuarioId);
            return View(asistencia);
        }

        // GET: Asistencias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asistencia = await _context.Asistencias
                .Include(a => a.Horario)
                .Include(a => a.Maquina)
                .Include(a => a.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asistencia == null)
            {
                return NotFound();
            }

            return View(asistencia);
        }

        // POST: Asistencias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var asistencia = await _context.Asistencias.FindAsync(id);
            if (asistencia != null)
            {
                _context.Asistencias.Remove(asistencia);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Finalizar));
        }

        private bool AsistenciaExists(int id)
        {
            return _context.Asistencias.Any(e => e.Id == id);
        }

        //Selecionar laboratorios
        public IActionResult SeleccionLab(int id, int idlab)
        {

            var maquinas = _context.Maquinas.Where(m => m.LaboratorioId == idlab).ToList(); // Cargar máquinas del laboratorio
            if (!maquinas.Any())
            {
                // Manejo de error o mensaje
                ViewBag.Mensaje = "No hay máquinas disponibles en este laboratorio.";
            }
            var usuario = _context.Usuarios.Find(id);
            var asistencia = new Asistencia
            {
                UsuarioId = id,
                Usuario = usuario
            };
            ViewBag.LaboratorioId = idlab;
            ViewBag.Maquinas = maquinas; // Pasar la lista de máquinas para que tambien vaya a la vista
            return View(asistencia);
        }
        public IActionResult Finalizar()
        {
            return View();
        }

    }
}

AppControlLaboratorios/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppControlLaboratorios.Data;
using AppControlLaboratorios.Models;

namespace AppControlLaboratorios.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly BDContexto _context;

        public UsuariosController(BDContexto context)
        {
            _context = context;
        }

        //Validaciones
        public bool IsCreatingUser { get; set; }

        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
            var bDContexto = _context.Usuarios.Include(u => u.Rol);
            return View(await bDContexto.ToListAsync());
        }


        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .Include(u => u.Rol)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            IsCreatingUser = true;
            ViewData["RolId"] = new SelectList(_context.Roles, "Id", "Id");
            return View();
        }


        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellidos,Correo,Contrasena,RolId")] Usuario usuario)
        {
            IsCreatingUser = false;
            if (ModelState.IsValid)
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RolId"] = new SelectList(_context.Roles, "Id", "Id", usuario.RolId);
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            ViewData["RolId"] = new SelectList(_context.Roles, "Id", "Id", usuario.RolId);
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellidos,Correo,Contrasena,RolId")] Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RolId"] = new SelectList(_context.Roles, "Id", "Id", usuario.RolId);
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .Include(u => u.Rol)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario != null)
            {
                _context.Usuarios.Remove(usuario);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Login
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        // POST: Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(Usuario usuario)
        {
            IsCreatingUser = false;
            if (ModelState.IsValid)
            {
                // Se busca el usuario en la base de datos por correo y contraseña
                var usuarioValido = await _context.Usuarios
                    .Include(u => u.Rol) // Incluir el rol del usuario
                    .FirstOrDefaultAsync(u => u.Correo == usuario.Correo && u.Contrasena == usuario.Contrasena);

                if (usuarioValido != null)
                {
                    // Dependiendo del Rol, se muestra una vista diferente
                    if (usuarioValido.Rol.Nombre == "Docente")
                    {
                        return View("VistaDocente", usuarioValido);
                    }
                    else if (usuarioValido.Rol.Nombre == "Estudiante")
                    {
                        return View("VistaEstudiante", usuarioValido);
                    }
                    else if (usuarioValido.Rol.Nombre == "Administrativo")
                    {
                        return View("VistaAdministrador", usuarioValido);
                    }
                }

                ModelState.AddModelError(string.Empty, "Intento de inicio de sesión no válido.");
            }
            return View(usuario); // Si algo falla, vuelve a mostrar la vista de login
        }
        public IActionResult VistaEstudiante(int idUsuario)
        {
            // Obtener el usuario desde la base de datos
            var usuario = _context.Usuarios.Find(idUsuario);

            // Verificar si el usuario fue encontrado
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }
        public IActionResult VistaDocente(int idUsuario)
        {
            // Obtener el usuario desde la base de datos
            var usuario = _context.Usuarios.Find(idUsuario);

            // Verificar si el usuario fue encontrado
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuarios.Any(e => e.Id == id);
        }
    }
}

AppControlLaboratorios/Views/Asistencias/Create.cshtml
@model AppControlLaboratorios.Models.Asistencia

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<body class="body">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3>Registrar Asistencia</h3>
                    </div>
                    <div class="card-body">
                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                            <div class="form-group mb-2">
                                <input asp-for="Observaciones" class="form-control" placeholder="Observaciones"/>
                                <span asp-validation-for="Observaciones" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-2">
                                <input asp-for="UsuarioId" class="form-control" readonly />
                            </div>
                            <div class="form-group mb-2">
                                <input asp-for="Usuario.Nombre" class="form-control" readonly />
                            </div>
                            <div class="form-group mb-2">
                                <input asp-for="MaquinaId" class="form-control" readonly />
                            </div>
                            <div class="form-group mb-2">
                                <input asp-for="Maquina.NumSerie" class="form-control" readonly />
                            </div>
                            <div class="form-group mb-2">
                                <select asp-for="HorarioId" class="form-control" asp-items="ViewBag.HorarioId"></select>
                                <span asp-validation-for="HorarioId" class="text-danger"></span>
                            </div>
                            <div class="form-group d-grid gap-2 mt-4">
                                <button type="submit" class="btn btn-success btn-lg btn-block">Crear</button>
                                <a asp-action="Index" class="btn btn-secondary btn-lg btn-block mt-2">Regresar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppControlLaboratorios/Views/Asistencias/Delete.cshtml
@model AppControlLaboratorios.Models.Asistencia

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Asistencia</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Observaciones)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Observaciones)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Maquina)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Maquina.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Horario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Horario.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AppControlLaboratorios/Views/Asistencias/Details.cshtml
@model AppControlLaboratorios.Models.Asistencia

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Asistencia</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Observaciones)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Observaciones)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Maquina)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Maquina.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Horario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Horario.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AppControlLaboratorios/Views/Asistencias/Edit.cshtml
@model AppControlLaboratorios.Models.Asistencia

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Asistencia</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Observaciones" class="control-label"></label>
                <input asp-for="Observaciones" class="form-control" />
                <span asp-validation-for="Observaciones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UsuarioId" class="control-label"></label>
                <select asp-for="UsuarioId" class="form-control" asp-items="ViewBag.UsuarioId"></select>
                <span asp-validation-for="UsuarioId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaquinaId" class="control-label"></label>
                <select asp-for="MaquinaId" class="form-control" asp-items="ViewBag.MaquinaId"></select>
                <span asp-validation-for="MaquinaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HorarioId" class="control-label"></label>
                <select asp-for="HorarioId" class="form-control" asp-items="ViewBag.HorarioId"></select>
                <span asp-validation-for="HorarioId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppControlLaboratorios/Views/Asistencias/Finalizar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container text-center mt-5">
    <div class="card shadow-sm">
        <div class="card-body">
            <h2 class="mb-4">Proceso finalizado</h2>
            <div class="row justify-content-center">
                <div class="col-12 col-md-4">
                    <a asp-controller="Usuarios" asp-action="Login" class="btn btn-danger btn-lg btn-block">Cerrar Sesión</a>
                </div>
            </div>
        </div>
    </div>
</div>

AppControlLaboratorios/Views/Asistencias/SeleccionLab.cshtml
@model AppControlLaboratorios.Models.Asistencia

@{
    var maquinas = ViewBag.Maquinas as List<AppControlLaboratorios.Models.Maquina>;
}
@if (ViewBag.Mensaje != null)
{
    <div class="alert alert-warning">@ViewBag.Mensaje</div>
}


<div class="container mt-5">
    <h2 class="text-white" style="text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.7);">Laboratorio: @ViewBag.LaboratorioId</h2>
    <h3 class="text-white" style="text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.7);">@Model.Usuario.Nombre , En que maquina estas?</h3>
    <div class="row section2-details py-5 d-flex justify-content-center align-items-center">
        <div class="bg-secondary border border-dark rounded mb-4 d-flex justify-content-center align-items-center" style="height: 50px;">
            <span class="text-white">Pizarra</span>
        </div>

        <table class="table table-borderless">
            <tbody>
                @if (ViewBag.LaboratorioId == 1 || ViewBag.LaboratorioId == 3) // Matriz para laboratorio 1 y 3
                {
                    int contador = 0;
                    @for (int i = 0; i < 7; i++)
                    {
                        <tr>
                            @for (int j = 0; j < 5; j++)
                            {


                                if (j % 5 == 2 || j == 2)
                                {

                                    <td>
                                        <a asp-controller="Asistencias" asp-action="Create" asp-route-usuarioId="@Model.UsuarioId" asp-route-maquinaId="@maquinas[contador].Id" class="btn btn-primary text-white w-100">@maquinas[contador].NumSerie</a>
                                    </td>
                                    <td>------</td>
                                }
                                else
                                {
                                    <td>
                                        <a asp-controller="Asistencias" asp-action="Create" asp-route-usuarioId="@Model.UsuarioId" asp-route-maquinaId="@maquinas[contador].Id" class="btn btn-primary text-white w-100">@maquinas[contador].NumSerie</a>
                                    </td>
                                }
                                contador++;

                            }
                        </tr>
                    }
                }

                @if (ViewBag.LaboratorioId == 2) // Matriz para laboratorio 2
                {
                    int contador = 0;
                    @for (int i = 0; i < 8; i++)
                    {
                        <tr>
                            @for (int j = 0; j < 4; j++)
                            {


                                if (j % 4 == 1 || j == 1)
                                {

                                    <td>
                                        <a asp-controller="Asistencias" asp-action="Create" asp-route-usuarioId="@Model.UsuarioId" asp-route-maquinaId="@maquinas[contador].Id" class="btn btn-primary text-white w-100">@maquinas[contador].NumSerie</a>
                                    </td>
                                    <td>------</td>
                                }
                                else
                                {
                                    <td>
                                        <a asp-controller="Asistencias" asp-action="Create" asp-route-usuarioId="@Model.UsuarioId" asp-route-maquinaId="@maquinas[contador].Id" class="btn btn-primary text-white w-100">@maquinas[contador].NumSerie</a>
                                    </td>
                                }
                                contador++;
                            }
                        </tr>
                    }
                }
                @if (ViewBag.LaboratorioId == 4) // Matriz para laboratorio 4
                {
                    int contador = 0;
                    @for (int i = 0; i < 4; i++)
                    {
                        <tr>
                            @for (int j = 0; j < 6; j++)
                            {
                                <td>
                                    <a asp-controller="Asistencias" asp-action="Create" asp-route-usuarioId="@Model.UsuarioId" asp-route-maquinaId="@maquinas[contador].Id" class="btn btn-primary text-white w-100">@maquinas[contador].NumSerie</a>
                                </td>
                                contador++;

                            }
                        </tr>
                    }
                }
            </tbody>

        </table>
    </div>
    <div>
        <a asp-controller="Usuarios" asp-action="VistaEstudiante" asp-route-idusuario="@Model.UsuarioId">Regresar</a>
    </div>
</div>