AppControlLaboratorios/Models/Usuario.cs
using AppControlLaboratorios.Models.Validaciones;
using System.ComponentModel.DataAnnotations;

namespace AppControlLaboratorios.Models
{
    public class Usuario
    {
        public int Id { get; set; }
        [Validacion]
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Correo { get; set; }
        [Display(Name = "Contraseña")]
        public string Contrasena { get; set; }
        public int RolId { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual ICollection<Horario> Horarios { get; set; }
        public virtual ICollection<Asistencia> Asistencias { get; set; }
        public ICollection<UsuarioCurso> UsuarioCursos { get; set; }
    }
}

AppControlLaboratorios/Controllers/AsistenciasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppControlLaboratorios.Data;
using AppControlLaboratorios.Models;

namespace AppControlLaboratorios.Controllers
{
    public class AsistenciasController : Controller
    {
        private readonly BDContexto _context;

        public AsistenciasController(BDContexto context)
        {
            _context = context;
        }

        // GET: Asistencias
        public async Task<IActionResult> Index(DateTime? fecha, int? idlab, int? idhorario)
        {
            // Obtener listas de laboratorios y horarios
            var laboratorios = await _context.Laboratorios.ToListAsync();
            var horarios = await _context.Horarios.ToListAsync();

            // Crear listas select para la vista
            ViewBag.Laboratorios = new SelectList(laboratorios, "Id", "LaboratorioNombre");
            ViewBag.Horarios = new SelectList(horarios, "Id", "CursoId");
            ViewBag.SelectedFecha = fecha;
            ViewBag.SelectedLab = idlab;
            ViewBag.SelectedHorario = idhorario;

            // Crear consulta inicial para las asistencias
            var bDContexto = _context.Asistencias
                .Include(a => a.Horario)
                .ThenInclude(c => c.Curso) // Relación entre Horario y Laboratorio
                .Include(a => a.Usuario) // Incluye la relación con Usuario
                .Include(a => a.Maquina) // Incluye la relación con Maquina
                .AsQueryable();


            // Filtro por Fecha
            if (fecha.HasValue)
            {
                bDContexto = bDContexto.Where(a =>
                    a.Fecha.Year == fecha.Value.Year &&
                    a.Fecha.Month == fecha.Value.Month &&
                    a.Fecha.Day == fecha.Value.Day);
            }


            // Filtro por Laboratorio
            if (idlab.HasValue && idlab.Value != 0)
            {
                bDContexto = bDContexto.Where(a => a.Maquina.LaboratorioId == idlab.Value);
            }

            // Filtro por Horario (HoraIni o HoraFin)
            if (idhorario.HasValue && idhorario.Value != 0)
            {
                bDContexto = bDContexto.Where(a => a.HorarioId == idhorario.Value);
            }

            // Obtener lista filtrada de asistencias
            var asistencias = await bDContexto.ToListAsync();

            return View(asistencias);
        }

        // GET: Asistencias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asistencia = await _context.Asistencias
                .Include(a => a.Horario)
                .Include(a => a.Maquina)
                .Include(a => a.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asistencia == null)
            {
                return NotFound();
            }

            return View(asistencia);
        }

        // GET: Asistencias/Create
        public IActionResult Create(int usuarioId, int maquinaId)
        {
            //Para que el reemplazar al horarioID
            var horarios = _context.Horarios
                .Include(h => h.Curso)  // Asegúrate de incluir la relación con el curso
                .Select(h => new {
                    h.Id,
                    DisplayText = h.Curso.CursoNombre + " (" + h.HoraIni + " - " + h.HoraFin + ")" // Formatear el texto para mostrarlo
                })
                .ToList();

            // Generar la lista de selección con el DisplayText personalizado
            ViewData["HorarioId"] = new SelectList(horarios, "Id", "DisplayText");

            var usuario = _context.Usuarios.Find(usuarioId);
            var maquina = _context.Maquinas.Find(maquinaId);
            var asistencia = new Asistencia
            {
                Usuario = usuario,
                Maquina = maquina,
                UsuarioId = usuarioId,
                MaquinaId = maquinaId
            };

            return View(asistencia);
        }


        // POST: Asistencias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Fecha,Observaciones,UsuarioId,MaquinaId,HorarioId")] Asistencia asistencia)
        {
            if (ModelState.IsValid)
            {
                asistencia.Fecha = DateTime.Now;
                _context.Add(asistencia);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["HorarioId"] = new SelectList(_context.Horarios, "Id", "Id", asistencia.HorarioId);
            return View(asistencia);
        }

        // GET: Asistencias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asistencia = await _context.Asistencias.FindAsync(id);
            if (asistencia == null)
            {
                return NotFound();
            }
            ViewData["HorarioId"] = new SelectList(_context.Horarios, "Id", "Id", asistencia.HorarioId);
            ViewData["MaquinaId"] = new SelectList(_context.Maquinas, "Id", "Id", asistencia.MaquinaId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Id", asistencia.UsuarioId);
            return View(asistencia);
        }

        // POST: Asistencias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Fecha,Observaciones,UsuarioId,MaquinaId,HorarioId")] Asistencia asistencia)
        {
            if (id != asistencia.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(asistencia);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AsistenciaExists(asistencia.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["HorarioId"] = new SelectList(_context.Horarios, "Id", "Id", asistencia.HorarioId);
            ViewData["MaquinaId"] = new SelectList(_context.Maquinas, "Id", "Id", asistencia.MaquinaId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Id", asistencia.UsuarioId);
            return View(asistencia);
        }

        // GET: Asistencias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asistencia = await _context.Asistencias
                .Include(a => a.Horario)
                .Include(a => a.Maquina)
                .Include(a => a.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asistencia == null)
            {
                return NotFound();
            }

            return View(asistencia);
        }

        // POST: Asistencias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var asistencia = await _context.Asistencias.FindAsync(id);
            if (asistencia != null)
            {
                _context.Asistencias.Remove(asistencia);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Finalizar));
        }

        private bool AsistenciaExists(int id)
        {
            return _context.Asistencias.Any(e => e.Id == id);
        }

        //Selecionar laboratorios
        public IActionResult SeleccionLab(int id, int idlab)
        {

            var maquinas = _context.Maquinas.Where(m => m.LaboratorioId == idlab).ToList(); // Cargar máquinas del laboratorio
            if (!maquinas.Any())
            {
                // Manejo de error o mensaje
                ViewBag.Mensaje = "No hay máquinas disponibles en este laboratorio.";
            }
            var usuario = _context.Usuarios.Find(id);
            var asistencia = new Asistencia
            {
                UsuarioId = id,
                Usuario = usuario
            };
            ViewBag.LaboratorioId = idlab;
            ViewBag.Maquinas = maquinas; // Pasar la lista de máquinas para que tambien vaya a la vista
            return View(asistencia);
        }
        public IActionResult Finalizar()
        {
            return View();
        }

    }
}

AppControlLaboratorios/Controllers/HorariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppControlLaboratorios.Data;
using AppControlLaboratorios.Models;

namespace AppControlLaboratorios.Controllers
{
    public class HorariosController : Controller
    {
        private readonly BDContexto _context;

        public HorariosController(BDContexto context)
        {
            _context = context;
        }

        // GET: Horarios
        public async Task<IActionResult> Index(int idUsuario)
        {
            var bDContexto = _context.Horarios.Include(h => h.Curso).Include(h => h.Laboratorio).Include(h => h.Usuario).AsQueryable();
            bDContexto = bDContexto.Where(a => a.UsuarioId == idUsuario);

            ViewBag.idUsuario = idUsuario;
            var horarios = await bDContexto.ToListAsync();
            return View(horarios);
        }


        // GET: Horarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var horario = await _context.Horarios
                .Include(h => h.Curso)
                .Include(h => h.Laboratorio)
                .Include(h => h.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (horario == null)
            {
                return NotFound();
            }

            return View(horario);
        }

        // GET: Horarios/Create
        public IActionResult Create(int idUsuario)
        {

            var horario = new Horario
            {
                UsuarioId = idUsuario
            };
            ViewData["CursoId"] = new SelectList(_context.Cursos, "Id", "CursoNombre");
            ViewData["LaboratorioId"] = new SelectList(_context.Laboratorios, "Id", "Id");

            return View(horario);
        }


        // POST: Horarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,HoraIni,HoraFin,UsuarioId,LaboratorioId,CursoId")] Horario horario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(horario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { idUsuario = horario.UsuarioId });
            }
            ViewData["CursoId"] = new SelectList(_context.Cursos, "Id", "CursoNombre", horario.CursoId);
            ViewData["LaboratorioId"] = new SelectList(_context.Laboratorios, "Id", "Id", horario.LaboratorioId);

            return View(horario);
        }


        // GET: Horarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var horario = await _context.Horarios.FindAsync(id);
            if (horario == null)
            {
                return NotFound();
            }
            ViewData["CursoId"] = new SelectList(_context.Cursos, "Id", "Id", horario.CursoId);
            ViewData["LaboratorioId"] = new SelectList(_context.Laboratorios, "Id", "Id", horario.LaboratorioId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Id", horario.UsuarioId);
            return View(horario);
        }

        // POST: Horarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,HoraIni,HoraFin,UsuarioId,LaboratorioId,CursoId")] Horario horario)
        {
            if (id != horario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(horario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HorarioExists(horario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CursoId"] = new SelectList(_context.Cursos, "Id", "Id", horario.CursoId);
            ViewData["LaboratorioId"] = new SelectList(_context.Laboratorios, "Id", "Id", horario.LaboratorioId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Id", horario.UsuarioId);
            return View(horario);
        }

        // GET: Horarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var horario = await _context.Horarios
                .Include(h => h.Curso)
                .Include(h => h.Laboratorio)
                .Include(h => h.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (horario == null)
            {
                return NotFound();
            }

            return View(horario);
        }

        // POST: Horarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var horario = await _context.Horarios.FindAsync(id);
            if (horario != null)
            {
                _context.Horarios.Remove(horario);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HorarioExists(int id)
        {
            return _context.Horarios.Any(e => e.Id == id);
        }
    }
}

AppControlLaboratorios/Views/Usuarios/Create.cshtml
@model AppControlLaboratorios.Models.Usuario

@{
    ViewData["Title"] = "Crear Usuario";
}

<body class="body">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3>Registrar Usuario</h3>
                    </div>
                    <div class="card-body">
                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                            <div class="form-group mb-2">
                                <input asp-for="Nombre" class="form-control" placeholder="Nombre" />
                                <span asp-validation-for="Nombre" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-2">
                                <input asp-for="Apellidos" class="form-control" placeholder="Apellidos" />
                                <span asp-validation-for="Apellidos" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-2">
                                <input asp-for="Correo" class="form-control" placeholder="Correo electrónico" />
                                <span asp-validation-for="Correo" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-2">
                                <input asp-for="Contrasena" class="form-control" type="password" placeholder="Contraseña" />
                                <span asp-validation-for="Contrasena" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-2">
                                <select asp-for="RolId" class="form-control" asp-items="ViewBag.RolId"></select>
                            </div>
                            <div class="form-group d-grid gap-2 mt-4">
                                <button type="submit" class="btn btn-success btn-lg btn-block">Crear</button>
                                <a asp-action="Index" class="btn btn-secondary btn-lg btn-block mt-2">Regresar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AppControlLaboratorios/Views/Usuarios/Delete.cshtml
@model AppControlLaboratorios.Models.Usuario

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contrasena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contrasena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rol)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rol.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AppControlLaboratorios/Views/Usuarios/Details.cshtml
@model AppControlLaboratorios.Models.Usuario

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contrasena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contrasena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rol)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rol.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AppControlLaboratorios/Views/Usuarios/Edit.cshtml
@model AppControlLaboratorios.Models.Usuario

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellidos" class="control-label"></label>
                <input asp-for="Apellidos" class="form-control" />
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contrasena" class="control-label"></label>
                <input asp-for="Contrasena" class="form-control" />
                <span asp-validation-for="Contrasena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RolId" class="control-label"></label>
                <select asp-for="RolId" class="form-control" asp-items="ViewBag.RolId"></select>
                <span asp-validation-for="RolId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppControlLaboratorios/Views/Usuarios/VistaDocente.cshtml
@model AppControlLaboratorios.Models.Usuario

<head>
    <title>@ViewData["Title"]</title>
</head>

<div>
    <div class="row section2-details py-5 d-flex justify-content-center align-items-center">
        <div class="col-md-6 text-center">
            <!-- Encabezado con el nombre del usuario -->
            <h1>¡ Bienvenido(a) @Model.Nombre @Model.Apellidos ! </h1>
        </div>
        <!-- Botones de laboratorio -->
        <div class="d-flex flex-column justify-content-center align-items-center mt-3">
            <!-- Botón con estilo personalizado -->
            <a asp-controller="UsuarioCursos" class="boton-vista text-light mb-2 margin:10px" asp-action="Index">
                Lista cursos
            </a>
            <a asp-controller="Horarios" class="boton-vista text-light mb-2 margin:10px" asp-action="Index">
                Lista Horarios
            </a>
        </div>
    </div>
</div>

<form asp-action="Login">
    <button class="salir">
        <div class="sign"><svg viewBox="0 0 512 512"><path d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z"></path></svg></div>
        <div class="text">Salir</div>
    </button>
</form>

AppControlLaboratorios/Views/Usuarios/VistaEstudiante.cshtml
@model AppControlLaboratorios.Models.Usuario
@{
}

<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
        <a class="navbar-brand text-white" href="#">
            <i class="fa-solid fa-house-laptop"></i>&nbsp;Laboratorios Sistemas
        </a>
    </div>
</nav>

<div>
    <div class="row section2-details py-5 d-flex justify-content-center align-items-center">
        <!-- Texto de bienvenida con sombra -->
        <h1 class="container text-center mb-4 text-white" style="text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.7);">¡Bienvenido @Model.Nombre!</h1>

        <!-- Pregunta con sombra -->
        <p class="container text-center lead mb-4 text-white" style="text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.7);">¿En qué laboratorio te encuentras?</p>

        <!-- Botones de laboratorio -->
        <div class="row justify-content-center">
            <div class="row justify-content-center">
                <div class="col-10 col-md-3 mb-3">
                    <form asp-controller="Asistencias" asp-action="SeleccionLab" asp-route-id="@Model.Id" asp-route-idlab="1">
                        <button type="submit" class="boton-vista text-light btn btn-primary btn-block">Laboratorio 01</button>
                    </form>
                </div>
                <div class="col-10 col-md-3 mb-3">
                    <form asp-controller="Asistencias" asp-action="SeleccionLab" asp-route-id="@Model.Id" asp-route-idlab="2">
                        <button type="submit" class="boton-vista text-light btn btn-primary btn-block">Laboratorio 02</button>
                    </form>
                </div>
            </div>

            <div class="row justify-content-center">
                <div class="col-10 col-md-3 mb-3">
                    <form asp-controller="Asistencias" asp-action="SeleccionLab" asp-route-id="@Model.Id" asp-route-idlab="3">
                        <button type="submit" class="boton-vista text-light btn btn-primary btn-block">Laboratorio 03</button>
                    </form>
                </div>
                <div class="col-10 col-md-3 mb-3">
                    <form asp-controller="Asistencias" asp-action="SeleccionLab" asp-route-id="@Model.Id" asp-route-idlab="4">
                        <button type="submit" class="boton-vista text-light btn btn-primary btn-block">Laboratorio 04</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Texto de cursos, horarios y asistencias-->
    <div class="container-fluid">
        <a class="navbar-brand text-white" href="#">
            <i class="fa-solid fa-house-laptop"></i>&nbsp;Laboratorios Sistemas
        </a>
    </div>
    <div class="row section2-details py-5 d-flex justify-content-center align-items-center">
        <!-- Botones de laboratorio -->
        <div class="row justify-content-center">
            <div class="col-10 col-md-3 mb-3">
                <form asp-controller="UsuarioCursos" asp-action="Index" asp-route-idUsuario="@Model.Id">
                    <button type="submit" class="boton-vista text-light btn btn-primary btn-block">Mis cursos</button>
                </form>
            </div>
            <div class="col-10 col-md-3 mb-3">
                <form asp-controller="Horarios" asp-action="Index" asp-route-idUsuario="@Model.Id">
                    <button type="submit" class="boton-vista text-light btn btn-primary btn-block">Mis Horarios</button>
                </form>
            </div>
            <div class="col-10 col-md-3 mb-3">
                <form asp-controller="Asistencias" asp-action="SeleccionLab" asp-route-idUsuario="@Model.Id" asp-route-idlab="3">
                    <button type="submit" class="boton-vista text-light btn btn-primary btn-block">Laboratorio 03</button>
                </form>
            </div>
        </div>
    </div>
</div>

<form asp-action="Login">
    <button class="salir">
        <div class="sign"><svg viewBox="0 0 512 512"><path d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z"></path></svg></div>
        <div class="text">Salir</div>
    </button>
</form>